baseURL = '/'
languageCode = 'en-us'
title = 'O11y toolkit'

[params]

geekdocMenuBundle = true
geekdocRepo = "https://github.com/o11ydev/oy-toolkit"

[params.geekdocContentLicense]
    name = "CC BY-SA 4.0"
    link = "https://creativecommons.org/licenses/by-sa/4.0/"
